/**
 * Alternate SEO paths → primary product URLs (cluster consolidation).
 * Keep in sync with scripts/seo/registry.ts SLUG_TO_PRIMARY.
 */
export const SLUG_TO_PRIMARY: Record<string, string> = {
  'video-to-text': '/video-to-transcript',
  'mp4-to-text': '/video-to-transcript',
  'mp4-to-srt': '/video-to-subtitles',
  'subtitle-generator': '/video-to-subtitles',
  'srt-translator': '/translate-subtitles',
  'meeting-transcript': '/video-to-transcript',
  'speaker-diarization': '/video-to-transcript',
  'video-summary-generator': '/video-to-transcript',
  'video-chapters-generator': '/video-to-transcript',
  'keyword-indexed-transcript': '/video-to-transcript',
  'srt-to-vtt': '/video-to-subtitles',
  'subtitle-converter': '/video-to-subtitles',
  'subtitle-timing-fixer': '/fix-subtitles',
  'subtitle-validation': '/fix-subtitles',
  'subtitle-translator': '/translate-subtitles',
  'multilingual-subtitles': '/translate-subtitles',
  'subtitle-language-checker': '/translate-subtitles',
  'subtitle-grammar-fixer': '/fix-subtitles',
  'subtitle-line-break-fixer': '/fix-subtitles',
  'hardcoded-captions': '/burn-subtitles',
  'video-with-subtitles': '/burn-subtitles',
  'video-compressor': '/compress-video',
  'reduce-video-size': '/compress-video',
  'batch-video-processing': '/batch-process',
  'bulk-subtitle-export': '/batch-process',
  'bulk-transcript-export': '/batch-process',
  'transcribe-video': '/video-to-transcript',
  'video-transcription': '/video-to-transcript',
  'free-transcription': '/video-to-transcript',
  'online-transcription': '/video-to-transcript',
  'ai-transcription': '/video-to-transcript',
  'audio-to-text': '/video-to-transcript',
  'podcast-transcript': '/video-to-transcript',
  'zoom-meeting-transcript': '/video-to-transcript',
  'zoom-recording-transcript': '/zoom-meeting-transcript',
  'meeting-recording-to-transcript': '/video-to-transcript',
  'transcribe-meeting-recording': '/meeting-recording-to-transcript',
  'meeting-transcription-tool': '/video-to-transcript',
  'interview-transcription': '/video-to-transcript',
  'lecture-transcription': '/video-to-transcript',
  'youtube-to-transcript': '/youtube-to-transcript',
  'youtube-transcript': '/youtube-to-transcript',
  'youtube-video-transcript': '/youtube-to-transcript',
  'transcribe-youtube-video': '/youtube-to-transcript',
  'youtube-to-text': '/youtube-to-transcript',
  'mov-to-text': '/video-to-transcript',
  'webm-to-text': '/video-to-transcript',
  'automatic-subtitles': '/video-to-subtitles',
  'caption-generator': '/video-to-subtitles',
  'closed-caption-generator': '/video-to-subtitles',
  'free-subtitle-generator': '/video-to-subtitles',
  'video-to-srt': '/video-to-subtitles',
  'srt-generator': '/video-to-subtitles',
  'translate-video': '/translate-subtitles',
  'video-translation': '/translate-subtitles',
  'bulk-video-transcription': '/batch-process',
  'otter-ai-alternative': '/otter-alternative',
}
